spring.application.name=nakama-hub-backend

spring.datasource.url=jdbc:mysql://localhost:3306/nakamahub
spring.datasource.username=root
spring.datasource.password=1501
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.include-message=always

# Security

spring.security.user.name=admin
spring.security.user.password=admin123

# Password de JWT
jwt.secret = un_password_super_complejo
jwt.expiration=86400000
